### ISSUE TITLE
Supporting on-demand loading of signatures from file lists in `search`, `gather`, and `prefetch`

### ISSUE THREAD

**Issue by luizirber** [sourmash-bio/sourmash#1096]
#1059 added `--from-file` to many commands, but not for `search` and `gather`.

Let's say, hypothetically, that a user has 2 million signatures in a directory and wants to run `sourmash search --containment` in some of them. Using `--traverse-directory` will try to load them all, which might have to use more than 3.5 TB of RAM. `--from-file` in this case would allow selecting a subset.

(there is, of course, the snakemake solution: run one `sourmash search --containment` for each signature to query against, and summarize later. But this is something that looks useful to have in `sourmash` instead of depending on a workflow manager)

**Comment by ctb** [comment]
I think lazy loading from a directory would be useful; right now, `load_file_as_signatures` does not do lazy loading of signatures, partly because of error handling. #810 proposes a Directory Index, could be explicitly made lazy. Would also want to check that search and gather support lazy.

**Comment by luizirber** [comment]
The other reason for this is that SBT and LCA are not ready for this use case scale, so `--from-file` with a `LinearIndex` is a stopgap to support it for now.

**Comment by ctb** [comment]
greyhound makes it possible to search signatures on this scale now - https://github.com/dib-lab/sourmash/issues/1226

**Comment by ctb** [comment]
Interesting addendum on this issue -- here, the hypothetical case could be looking at signatures that are quite large, e.g. from metagenomes. It is not my usual mental assumption that signatures are really big, but obviously they are larger than a string would be.

**Comment by ctb** [comment]
This should be something that `sourmash prefetch` can support. May or may not make it into #1370 tho.

**Comment by ctb** [comment]
I'm going to stick a "good next issue" tag on this, since `--load-from-file` functionality should be pretty easy to implement here, and this is mostly about providing tests!

See the code in `src/sourmash/commands.py:compare(...)` for the if statement to use (`if args.from_file`).

Would need to add `--from-file` to the CLI options in `src/sourmash/cli/search.py`, `gather.py`, and `prefetch.py`.

And then... testing...!

**Comment by ctb** [comment]
> #1059 added `--from-file` to many commands, but not for `search` and `gather`.
> 
> Let's say, hypothetically, that a user has 2 million signatures in a directory and wants to run `sourmash search --containment` in some of them. Using `--traverse-directory` will try to load them all, which might have to use more than 3.5 TB of RAM. `--from-file` in this case would allow selecting a subset.

Note that `LazyMultiIndex` in #1590 is close to supporting this use case now, with only a little big of jiggery pokery. Briefly,
* put each signature them in a .zip collection with a manifest;
* load all the zip collections into `LazyMultiIndex` (which won't load the signatures);
* do your selects etc if you so desire;
* run `find`, which in this case will run `.signatures_with_location()` underneath, which does full lazy loading of signatures based on manifests;

This is a bit hacky because of the need to put the sig files in a .zip collection. "All" that would be needed to make this fully lazy _without_ stuffing the signatures into a zip file would be a way to designate a manifest for a .sig file. That is a good idea IMO :). I'll play around with it!

**Comment by luizirber** [comment]
> This is a bit hacky because of the need to put the sig files in a .zip collection. "All" that would be needed to make this fully lazy _without_ stuffing the signatures into a zip file would be a way to designate a manifest for a .sig file. That is a good idea IMO :). I'll play around with it!

I think this works with a fake `FSStorage` too (which can be a tempdir) as long as we use absolute paths for the storage.

**Comment by ctb** [comment]
whups, forgot to set up a PR for this - see https://github.com/sourmash-bio/sourmash/pull/1619

**Comment by ctb** [comment]
relevant to the original topic of this issue: https://github.com/sourmash-bio/sourmash/issues/1631

**Comment by ctb** [comment]
see #1641 for an alternative approach for searching large collections of signatures (we should still support `--from-file`, of course!)

**Comment by ctb** [comment]
this seems relevant... manifests of manifests! https://github.com/sourmash-bio/sourmash/issues/1685

**Comment by ctb** [comment]
Re-reading all of this, especially in the context of https://github.com/sourmash-bio/sourmash/pull/1891, I think that the relevant functionality here is provided by manifests and picklists (specifically, the lazy loading functionality / internal location information present in manifests) and `prefetch` (for the linear search), with `StandaloneManifestIndex`, `SBT`, and `ZipFileLinearIndex` fully supporting on-demand/lazy loading of signatures.

I'll leave this open 'til I have the mental space to experiment with it and make sure that prefetch does the right thing with lazy loading / streaming input and output.

**Comment by ctb** [comment]
This is supported by #1891! I added an explicit test in 38593b6f9.
