### ISSUE TITLE
Identifying groups of samples for co-assembly

### ISSUE THREAD

**Issue by adityabandla** [sourmash-bio/sourmash#1212]
Hello sourmash team, 
I am trying to use sourmash to identify groups of samples (based on shared k-mer content) for co-assembly. Resemblance computed using --scaled or -n=5e6 (or anything greater than 1e6?) followed by clustering is one way. 

Another way, which I'm keen to explore is to cluster samples based on number of k-mers that they share for a given number of hashes (say 1e6). Is there a way to get this out from the sourmash results? Resemblance & containment both normalise it according to either union or size of the reference

Cheers, Adi

**Comment by ctb** [comment]
hi adi! thanks for asking!

A couple off-the-cuff comments first --
* this is for metagenomes, I assume?
* scaled=1000 is going to be pretty effective, and will support containment analysis. I think this is exactly what you want.
* -n=5e6 is way too large and will be really inefficient to compute, and will also only support similarity; you can't do robust hash overlap computations with it, because there is no guarantee that a hash that is present in both data sets and shows up in one sketch will show up in the other sketch. (scaled *does* provide this guarantee.)

On to the central question - there is no simple way to use the sourmash command line to compute exactly what you want to do, although it is readily doable via the sourmash Python API.

* the simplest way to get the numbers you want from the command line is to do pairwise `sourmash sig overlap` computations, which will give you the estimated number of shared k-mers. See the `number of hashes in common` output field. You'd have to do this for all pairs manually, though.
* realistically, I think you're going to get similar results if you do `sourmash compare --containment *.sig -o contain` and then do `sourmash plot contain`, and then examine the clusters.

That having been said, I'm happy to hack together a script that will do this via the Python API, but it would probably be a few days at least :).

**Comment by ctb** [comment]
hmm this could be added to / be a modification of #1265 uniqify, I think.

**Comment by ctb** [comment]
`sourmash prefetch`, released in [sourmash 4.1.0](https://github.com/sourmash-bio/sourmash/releases/tag/v4.1.0), contains the un-normalized information needed here!

**Comment by ctb** [comment]
closing, since sourmash prefetch provides the necessary information.
