### ISSUE TITLE
How to extract reads from the different organisms?

### ISSUE THREAD

**Issue by josruirod** [sourmash-bio/sourmash#1237]
Hi and thanks for the software.

I was wondering if I could use this for separating reads for different organisms in an RNA-seq experiemnt. I gave it a try and I got the % of the reads assigned to each of the organisms, but can I extract the reads for each of them? Could anyone point me to a tutorial or to the proper arguments or functions?

Thank you very much for the support

**Comment by ctb** [comment]
hi @josruirod one way to do so is by mapping the reads to the reference transcriptomes identified by sourmash gather. However, it is tricky to do this properly because you could have reads that map to multiple organisms. I've been building a workflow to do this for metagenomes & genomes, [over in the genome-grist project](https://github.com/dib-lab/genome-grist), and some of those approaches might work for you - in particular, take a look at

* [the minimap rule](https://github.com/dib-lab/genome-grist/blob/latest/genome_grist/conf/Snakefile#L148)
* [the extract_leftover_reads rule](https://github.com/dib-lab/genome-grist/blob/latest/genome_grist/conf/Snakefile#L269)
* [the map_leftover_reads rule](https://github.com/dib-lab/genome-grist/blob/latest/genome_grist/conf/Snakefile#L286)
* the [subtract_gather script](https://github.com/dib-lab/genome-grist/blob/latest/genome_grist/subtract_gather.py)

Unfortunately this is at the moment highly tailored to a particular directory structure and set of commands, so adapting it may be difficult. Unless you're comfortable with snakemake, I'd suggest writing a shell script to do the commands in order, and then if/as you need help you can post it here and I can help you debug it and adjust the subtract_gather script appropriately!

**Comment by ctb** [comment]
(but, serendipity! at least I've been working on this recently 😆 )

**Comment by josruirod** [comment]
Hi, nice! Indeed it's going to happen that the reads map to multiple organisms. I'll review all the documentation that you have shared and let you know if we try to adapt it. I'm confident with bash but not with snakemake. Thanks for the work and the kind suggestions!

What input would the subtract_gather.py need? Thanks!

**Comment by ctb** [comment]
+1 - ask for help as you need it! My scripts always benefit from more use
cases!

**Comment by ctb** [comment]
I'm going to close this for now - ask as you have questions and we can reopen!

**Comment by ctb** [comment]
(actually closed this :)
