### ISSUE TITLE
add name, md5 of query signature to gather and search output

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1247]
courtesy of Courtney's rotation project, sometimes you want to do big database searches and combine all CSVs and figure out which ones match to which query, and right now you can't...

**Comment by ctb** [comment]
Some suggestions on how to do this:

* in `src/sourmash/search.py`, add `query_name` and `query_md5` to the `GatherResult` `namedtuple`
* set the values appropriately in `gather_databases` (should be the original `query.md5sum()[:8]` and `str(query)`
* make sure they are output properly in `src/sourmash/commands.py` by the `gather` and `multigather` functions.
* augment existing tests in `tests/test_sourmash.py` to check for these two fields in the CSV output - `test_gather_csv` looks like a good test, but there might be others.

**Comment by ctb** [comment]
fixed in #1346.

**Comment by bluegenes** [comment]
@ctb -- this was added to `search` but not `gather` output, right?
(ref: https://github.com/dib-lab/sourmash/blob/latest/src/sourmash/search.py#L369-L384)

Would be really handy to have this for `sourmash tax classify`. 

use case: have 1000 MAGs to classify. Want to input 1000 gather result files (e.g. `--from-file`) and get a single csv output with the best classification for each MAG. Would be need to be able to get that directly from gather rather than relying on the user to provide the right `query_name: gather_csv` mapping

**Comment by ctb** [comment]
right, it's available in the prefetch output, but not the gather output.

**Comment by ctb** [comment]
fixed for gather over in #1565.
