### ISSUE TITLE
query was calculated with scaled, tree was not.

### ISSUE THREAD

**Issue by J-I-P** [sourmash-bio/sourmash#1273]
Hi, I try to build my SBT database, but I get some problems.
There is my command below:
1. I use `computes`  to saves signatures for NCBI sequence.
`find . -name '*' | xargs sourmash compute --output NCBI_genome_ALL`
![image](https://user-images.githubusercontent.com/17896123/104260085-b3fa2780-54bd-11eb-82ae-f4500640c8c9.png)
The picture is my output describe
2. Index to build SBT database
`sourmash index -k 31 NCBI.sbt.zip NCBI_genome_ALL`
3. And then, `gather` the sequence
`sourmash gather zymoLOG_after_medaka.fasta.sig ../NCBI.sbt.json`
When I create zymoLOG_after_medaka.fasta.sig I used `--scaled=1000`.

But I get the result like below:
![image](https://user-images.githubusercontent.com/17896123/104258930-654b8e00-54bb-11eb-9ef1-da1773778e31.png)
I get this response because when I compute the NCBI sequence didn't use `--scaled`?
I should try to add `--scaled=10000`?

Thanks for any advice on this!

**Comment by ctb** [comment]
yes, I think so!
> ![image](https://user-images.githubusercontent.com/17896123/104258930-654b8e00-54bb-11eb-9ef1-da1773778e31.png)
> I get this response because when I compute the NCBI sequence didn't use `--scaled`?
> I should try to add `--scaled=10000`?

yes, that should fix it!

best,
--titus

**Comment by J-I-P** [comment]
Hi, @ctb, 
I have a doubt about my step 1.
![image](https://user-images.githubusercontent.com/17896123/104560593-0e8fb100-5681-11eb-930d-a57f6a8696f6.png)
I use `compute` to saves signatures for NCBI sequence.
There are 182666 .gz files in this directory, but this picture shows computing signatures for files only 2921 .gz files.
Is this correct? or something I get wrong?
Thank you for your reply.

**Comment by ctb** [comment]
hmm, you might want to use `--outdir` instead of `--output`? if I'm reading the command correctly, and if I remember how xargs works, you are running `sourmash compute` on batches of files, and `--output` will combine each batch into a single signature.

I tried this command:
```
find . -name '*.fa' | xargs sourmash compute --scaled=1000 --output xyz
```
on a smaller collection of sequences with `xyz/` being a directory and it failed, because `--output` needs to be a filename. So I'm not sure what's happening with your command - is `NCBI.genomes.k31.s1000` a directory, or a file, or what?

This command worked fine:
```
find . -name '*.fa' | xargs sourmash compute --scaled=1000 --outdir xyz
```

**Comment by J-I-P** [comment]
> hmm, you might want to use `--outdir` instead of `--output`? if I'm reading the command correctly, and if I remember how xargs works, you are running `sourmash compute` on batches of files, and `--output` will combine each batch into a single signature.
> 
> I tried this command:
> 
> ```
> find . -name '*.fa' | xargs sourmash compute --scaled=1000 --output xyz
> ```
> 
> on a smaller collection of sequences with `xyz/` being a directory and it failed, because `--output` needs to be a filename. So I'm not sure what's happening with your command - is `NCBI.genomes.k31.s1000` a directory, or a file, or what?
> 
> This command worked fine:
> 
> ```
> find . -name '*.fa' | xargs sourmash compute --scaled=1000 --outdir xyz
> ```

My `NCBI.genomes.k31.s1000` is a file. If after I use `--outdir`, I also can use `sourmash index` to build a SBT database?

**Comment by ctb** [comment]
> My `NCBI.genomes.k31.s1000` is a file. If after I use `--outdir`, I also can use `sourmash index` to build SBT database?

yes!

**Comment by J-I-P** [comment]
Hi, @ctb  
How you bulid `refseq-k31.sbt.json` database?
I have a wear problem with my database (SBT).
![image](https://user-images.githubusercontent.com/17896123/104853427-ba642580-593b-11eb-8916-a75739cd18d7.png)
The blue word is my diectory, and I index it to .sbt.zip.
I try to build all .gz of genomes in NCBI (ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/), how about your refseq-k31 database?

![image](https://user-images.githubusercontent.com/17896123/104853590-da481900-593c-11eb-9b42-97396745eb15.png)
This picture is using your database, and the result is correct and perfect!!

But when I use my database is like below:
![image](https://user-images.githubusercontent.com/17896123/104853620-0f546b80-593d-11eb-95bc-c2989c9a6657.png)
The overlap is less than your result, so I think there is some trouble in my database. But I have no idea how to check about my .sbt.zip or .sig file?

Thanks for any advice on this!

**Comment by ctb** [comment]
hi @J-I-P,

hmm, interesting. To me it looks like everything is working fine technically, which makes me wonder if the database contents are different. Can you try doing a search for that first pseudomonas match from refseq in your database, and see what it reports?

I am not 100% clear on what is in RefSeq, vs what is in GenBank.

**Comment by J-I-P** [comment]
> hi @J-I-P,
> 
> hmm, interesting. To me it looks like everything is working fine technically, which makes me wonder if the database contents are different. Can you try doing a search for that first pseudomonas match from refseq in your database, and see what it reports?
> 
> I am not 100% clear on what is in RefSeq, vs what is in GenBank.


![image](https://user-images.githubusercontent.com/17896123/104854060-dec20100-593f-11eb-9a14-f0ebf305c85e.png)
This is the first pseudomonas in your database, and its assembly is GCF_000504485.1
![image](https://user-images.githubusercontent.com/17896123/104854175-45471f00-5940-11eb-9bb7-38e690ef0670.png)
So I try to search this assembly in my database directory before index, and it can find the .sig file.

**Comment by ctb** [comment]
ok - and when you do a sourmash gather on that specific genome signature in the new database you constructed, you don’t find that match right?

could you post the text versions (not screenshots, please :) of the commands you used to index the database?

thanks,
—titus

**Comment by J-I-P** [comment]
There is my command:  `find . -name '*.sig' | xargs sourmash index -k 31 ../NCBI_test_dir.sbt.zip`
thanks for your reply. :)

**Comment by ctb** [comment]
hi nicole,

I think you’re running into the same problem as before, and xargs is only passing in a few signatures at a time.

Try instead:

sourmash index -k31 output.sbt.zip ./

which will load in all the signature files in the current directory.

best,
—titus

**Comment by J-I-P** [comment]
But this command will occur ERROR like this : `OSError: Error while reading signatures from './'.`

**Comment by ctb** [comment]
On Sun, Jan 17, 2021 at 12:59:33PM -0800, Nicole wrote:
> But this command will occur ERROR like this : `OSError: Error while reading signatures from './'.`

hmm, what version of sourmash are you using? 3.5.x should support that.

you might need to add `--traverse-directory -f` for your version.

--t

**Comment by ctb** [comment]
sorry, I was incorrect, the new behavior is on by default in only the pre-4.0 releases. In 3.5.0, you'll need to provide `--traverse-directory` to sourmash index in order to use `./` as an argument successfully.

**Comment by J-I-P** [comment]
I will try to use `--traverse-directory -f` what you suggest.
Thanks for your advice. :) 👍

**Comment by ctb** [comment]
welcome & please let me know!

**Comment by J-I-P** [comment]
> welcome & please let me know!

It works perfectly!!!:)
But the result also has false-positive like Mash screen.
That let me confused, both of these two tools use modulo to sketch the scale. The biggest difference is the reference database? SBT has more expandable than .msh? ( Mash screen rather than use a bloom filter, they use an exact, streaming method to identify which sketch values are found in the sample. Because they think bloom filter will cause [false-positive](https://genomeinformatics.github.io/mash-screen/))
Is there another advantage of sourmash is better than Mash screen?
Of course, you provide python API is more convenient. 👍 
Thanks for advice on this!

**Comment by ctb** [comment]
Hi Nicole,

I’ll address the differences and similarities between mash and sourmash in another message, but our experience is that we don’t observe many false positives. How are you benchmarking the results?

We have some workflows in development that compare hash values (as output by sourmash) with mapped reads (using minimap2). I’d be happy to point you at them if you are interested in comparing the output of sourmash gather output and the mapping rates of metagenome reads to the references. However, at the moment they are pretty focused on mapping to NCBI genomes, so it wouldn’t be immediately usable for custom databases. (see github.com/dib-lab/genome-grist for the tool).

best,
—titus

**Comment by J-I-P** [comment]
Sorry, I find that my overlap of results still smaller than yours data. Pseudomonas aeruginosa can up to 6.8 Mbp, but my overlap is only 690kbp. Does it connect to scaled size? my database scaled size is 1000.

**Comment by J-I-P** [comment]
> Hi Nicole, I’ll address the differences and similarities between mash and sourmash in another message, but our experience is that we don’t observe many false positives. How are you benchmarking the results? We have some workflows in development that compare hash values (as output by sourmash) with mapped reads (using minimap2). I’d be happy to point you at them if you are interested in comparing the output of sourmash gather output and the mapping rates of metagenome reads to the references. However, at the moment they are pretty focused on mapping to NCBI genomes, so it wouldn’t be immediately usable for custom databases. (see github.com/dib-lab/genome-grist for the tool). best, —titus

You don't observe many false-positives with default `--threshold-bp` (50kbp)?
My test data is from [zymo community].(https://files.zymoresearch.com/protocols/_d6310_zymobiomics_microbial_community_standard_ii_(log_distribution).pdf) Before I use sourmash, I assembly it.
This table is the composition of my data (metagenome)
![image](https://user-images.githubusercontent.com/17896123/104986687-862d5980-5a4e-11eb-8965-e490c0a96b74.png)
I try to use `sourmash gather` with `--threshold-bp` to figure out that eight bacteria (Listeria monocytogenes (89.1%) , Pseudomonas aeruginosa (8.9%), Bacillus subtilis (0.89%), Escherichia coli (0.089%), Salmonella enterica (0.089%), Lactobacillus fermentum (0.089%), Enterococcus faecalis (0.00089%), Staphylococcus aureus (0.000089%)). 
When I use `--threshold-bp`  by default, and use your refseq-database the result is only figured out Listeria monocytogenes, Pseudomonas aeruginosa, Bacillus subtilis, Escherichia coli, Salmonella enterica. Is that because the other three bacteria are too less  reads to figure out? (or your ref-seq does not have other three bacteria  data?)

**Comment by J-I-P** [comment]
> > Hi Nicole, I’ll address the differences and similarities between mash and sourmash in another message, but our experience is that we don’t observe many false positives. How are you benchmarking the results? We have some workflows in development that compare hash values (as output by sourmash) with mapped reads (using minimap2). I’d be happy to point you at them if you are interested in comparing the output of sourmash gather output and the mapping rates of metagenome reads to the references. However, at the moment they are pretty focused on mapping to NCBI genomes, so it wouldn’t be immediately usable for custom databases. (see github.com/dib-lab/genome-grist for the tool). best, —titus
> 
> You don't observe many false-positives with default `--threshold-bp` (50kbp)?
> My test data is from [zymo community].(https://files.zymoresearch.com/protocols/_d6310_zymobiomics_microbial_community_standard_ii_(log_distribution).pdf) Before I use sourmash, I assembly it.
> This table is the composition of my data (metagenome)
> ![image](https://user-images.githubusercontent.com/17896123/104986687-862d5980-5a4e-11eb-8965-e490c0a96b74.png)
> I try to use `sourmash gather` with `--threshold-bp` to figure out that eight bacteria (Listeria monocytogenes (89.1%) , Pseudomonas aeruginosa (8.9%), Bacillus subtilis (0.89%), Escherichia coli (0.089%), Salmonella enterica (0.089%), Lactobacillus fermentum (0.089%), Enterococcus faecalis (0.00089%), Staphylococcus aureus (0.000089%)).
> When I use `--threshold-bp` by default, and use your refseq-database the result is only figured out Listeria monocytogenes, Pseudomonas aeruginosa, Bacillus subtilis, Escherichia coli, Salmonella enterica. Is that because the other three bacteria are too less reads to figure out? (or your ref-seq does not have other three bacteria data?)

When I use `sourmash gather` with `--threshold-bp=0` and refseq-database, that three species is not in the result, but occur another species (except that eigth species)

**Comment by J-I-P** [comment]
And I'm so curious that how you reduce false-positive when you use bloom filter? (use more hash functions or some other method?)

**Comment by ctb** [comment]
so many questions 😆 

let's see - 

first, there's an excellent description of sourmash (with comparisons to mash screen and cmash) in @luizirber thesis, [here](https://github.com/luizirber/phd/releases/tag/2020.09.28). Chapters 1-3 are the most relevant. We are working on putting that into a publication, but it's still in early draft stage [here](https://github.com/dib-lab/2020-paper-sourmash-gather/).

Some specific answers -

Bloom filters do present false positives, but with SBTs we use them as an aid in searching, not as the final match. So the list of signatures you get with scores and so on are the actual hash matches, not anything to do with Bloom filters. You can try this out by using `--save-matches` with `sourmash gather`, which will output just a list of the matching signatures; you'll get the same result running `sourmash gather <query.sig> <saved_matches.sig>` as you do running `sourmash gather <query.sig> <database.sbt.zip>`.  (If not, it's a bug ;).

mash uses MinHash, sourmash with `scaled` uses a variant of modulo hash. They are roughly equivalent for similarity calculations, but sourmash with `scaled` allows containment searches on already-sketched databases of genomes, while `mash screen` does a separate thing that requires re-sketching the raw data.

Our results with genome-grist and in the sourmash draft paper, above, confirm to us that we in general do not get false positives with sourmash. (You wouldn't expect to, statistically, either!) If anything we worry more about false negatives due to the very high specificity of k-mers.

I haven't looked at the Zymo community myself, but a few notes -
* yes! the lower abundance stuff will probably have too few reads or k-mers, and `--threshold-bp` does help by adjusting the threshold for matching lower! The problem of false negatives due to low abundance is somewhat unavoidable - we know sourmash will have trouble with small genomes and/or undersampled genomes - and I would guess the threshold would be around a few thousand reads from those genomes, below which detection would be impossible.
* That having been said, I would suggest NOT assembling the metagenome. Assembly is a big filtering step that throws away most low-abundance k-mers.
* I'm pretty sure refseq has all of those genomes. It would be interesting to analyze this community with the minimap2 approach we're using in genome-grist, to see if read mapping matches...!

I hope that all helps :).

The biggest thing I would suggest is redoing the analysis without an assembled metagenome, i.e. by recalculating the query on the raw reads.

The second biggest thing I would suggest (by way of benchmarking...) is to compare read mapping of the metagenome to the genomes that are *supposed* to be there to the mapping to the genomes that sourmash is finding. I would expect the results to match w/sourmash's results, i.e. that sourmash is finding strains and genomes that are really there. (This is a lot of work tho!)

**Comment by ctb** [comment]
p.s. if you can give me the .sig file calculated from the raw reads with `-k 31 --scaled=1000` I can run it against all 700,000 genbank genomes and give you the mapping breakdown to the sourmash matches using genome-grist. Just drop me the signature file at titus@idyll.org.

**Comment by ctb** [comment]
Closing for now.
