### ISSUE TITLE
maybe add new command, `sourmash prefetch`

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1310]
I'm a big fan of the [`prefetch_gather` functionality in genome-grist](https://github.com/dib-lab/genome-grist/blob/latest/genome_grist/prefetch_gather.py) that pulls out overlapping signatures from a large database for the purpose of doing downstream gather and other things, and it seems like https://github.com/dib-lab/sourmash/pull/1238 is going to be adding the related functionality from greyhound #1226 into sourmash. However, I am wondering if there's value in explicitly adding a Python-based sourmash CLI function, `sourmash prefetch`, that would let us explore the behavior in non-Rust code. It seems like it would be generically useful to have it be available, and it would also prevent us from copy-pasting `prefetch_gather` over to other projects like charcoal and maybe thumper...

**Comment by luizirber** [comment]
As supporting datapoint, yesterday I worked a bit on bringing the [counter gather][0] from greyhound into Python, and there is a bit of the functionality that is shared with `prefetch`.

I think it's small enough to be available in `sourmash`, especially since it's being copy-and-pasted into multiple projects :upside_down_face: 

[0]: https://github.com/dib-lab/sourmash/pull/1311

**Comment by ctb** [comment]
idle early morning thought - double check that the prefetch approach works for `similarity` and `max_containment` too.

**Comment by ctb** [comment]
also struck by the basic similarity between the behavior of `prefetch` and `search --containment`.
