### ISSUE TITLE
support `--from-file` in `sig cat`

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash#1631]
We now support building a `ZipFile` collection of signatures using `sig cat`, e.g. `sourmash sig cat *sigs -o sigs.zip`. It would be nice to support `--from-file` here to be able to zip up signatures from a list of sig file paths.

**Comment by klamens** [comment]
Idem for "sig merge"

**Comment by ctb** [comment]
From an internals perspective, at this point maybe we want to unify the code for loading multiple signatures under a single set of functions for (a) adding signature loading to a subparser, and (b) loading the list of signatures so that it automatically includes `--from-file`? Then we can just add that everywhere.

**Comment by ctb** [comment]
I'm going to keep this open as part of a broader `--from-file` addition goal :)
