### ISSUE TITLE
Multiple queries to gather

### ISSUE THREAD

**Issue by andrewjmc** [sourmash-bio/sourmash#1681]
Hello,

How does sourmash behave if multiple queries are put in one gather command?

I have an instance where running a single query gives me this:

```
loaded query: 102-4852.2020-12-12_143_hg_bin... (k=21, DNA)
loaded 1 databases.

Starting prefetch sweep across databases.
Found 8 signatures via prefetch; now doing gather.

overlap     p_query p_match
---------   ------- -------
141.0 kbp     38.0%    6.0%    GCA_902373545.1 uncultured Actinomyce...
found less than 50.0 kbp in common. => exiting
```

However, loading the same signature + 9 others from a picklist gave this:

```
picking column 'ID' of type 'name' from 'to_gather.txt'
loaded 10 distinct values into picklist.
selecting specified query k=21
loaded query: 102-4852.2020-12-12_143_hg_bin... (k=21, DNA)
loaded 10 signatures and 1 databases total.

Starting prefetch sweep across databases.
Found 0 signatures via prefetch; now doing gather.
found less than 50.0 kbp in common. => exiting
```

I'm unsure whether gather was going to do what I wanted anyway, since I would look for results broken down by signature. I only wanted a single call so the database would be loaded once only.

**Comment by ctb** [comment]
my goodness you are on the bleeding edge with picklists etc - I love it!

First, this was the reason we implemented multigather, so you *might* try that command. It supports multiple queries via `--query` and multiple databases via `--db`. It might be frustrating since it's sort of the ugly step-sibling of `gather` (which we use all the time ourselves, unlike multigather).

Second, `gather` should not permit multiple queries, and should print out an error message when multiple queries are given (e.g. multiple sigs in a single input file with no unambiguous single query to choose). You _could_ use `sourmash sig merge` to merge all your queries into a single signature, then use `prefetch` to save the matches into a new database, and then run gather individually on that new database. ...messy, I know. Let me know if you'd like me to spell that out more. It _should_ be as simple as (1) `sourmash sig merge queries.sig -o combined.sig`, then (2) `sourmash prefetch combined.sig <databases> -o prefetch-matches.zip`, and then (3) `sourmash gather query1.sig prefetch-matches.zip`.

Third, picklists apply to databases, not queries. So I _think_ what you're doing is eliminating everything from your databases. I feel like prefetch should be saying something about that, tho, so ... I will look into that. And if that is indeed the problem, please let us know if you have thoughts for documentation improvement and clarity! 😆

**Comment by andrewjmc** [comment]
Ah, first big misunderstanding - I had guessed picklists were selecting from queries, rather than filtering signatures in the database. In my case, a combined query signature would be unhelpful as I'm interested in the gather results for each independent query. Multigather (appears top secret!) looks like the way -- hope it will handle 12k signatures!

**Comment by ctb** [comment]
let me know how we can help! Note `--query-from-file` argument, so that should work for ya.

you might be interested in https://github.com/sourmash-bio/sourmash/issues/909 but it is not (yet) a solution.

also, if you're using LCA databases for taxonomy reasons, I would love to point you in the direction of `sourmash taxonomy`... and if you're not using LCA databases for taxonomy reasons, SBTs might offer improved performance on loading, and permit more parallelism.

**Comment by andrewjmc** [comment]
Thanks, working a treat!

**Comment by andrewjmc** [comment]
Except... where's the output CSV from multigather?

**Comment by ctb** [comment]
It should be in `$(basename queryfile).csv` based on the source code ;). So, *.csv in the CWD.

**Comment by ctb** [comment]
...feedback solicited... <grin>
