### ISSUE TITLE
look into upgrading rust

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1694]
per https://twitter.com/rustlang/status/1420751620321660930, 1.54.0 is out.

- [x] CI/GitHub actions
- [x] conda-forge build
- [x] ???

**Comment by luizirber** [comment]
> per https://twitter.com/rustlang/status/1420751620321660930, 1.54.0 is out.
> 
>     * [ ]  CI/GitHub actions

CI pulls "stable"/"beta"/"nightly", so they will be updated accordingly as new versions are released.

> conda-forge build

we don't really require latest and greatest to compile sourmash. We actually limit to [`>1.37.0` (MSRV) and `<1.48`](https://github.com/conda-forge/sourmash-minimal-feedstock/blob/223081480e121569f739aecd38778e62df0d4454/recipe/meta.yaml#L24) because macOS had issues building newer versions of Rust (but seems to be back to normal, so we might do a build increment and remove the limit once https://github.com/conda-forge/rust-feedstock/pull/85 is merged and available in conda-forge. Actually, it needs to be updated to `>1.42`, since the MSRV for Rust is not `1.37` anymore :sweat_smile: 
 
>     * [ ]  ???

Nix. I tend to make some PRs including the command to update the environment (`niv update`), I'll open one (since we don't need to change anywhere else here in this repo). It is also likely that new `clippy` errors might trigger in `beta`, so I might make one PR for both.

**Comment by pkgw** [comment]
I saw that you linked this issue to the conda-forge PR. If the Rust/macOS issue that you're referring to is related to rust-feedstock/issues#73, then FYI I've been told that the fix didn't quite make it into 1.54, and will hit stable in 1.55.

**Comment by luizirber** [comment]
Fixed by https://github.com/conda-forge/sourmash-minimal-feedstock/pull/25
