### ISSUE TITLE
Preconfigured databases with both eukaryotes and prokaryotes?

### ISSUE THREAD

**Issue by jolespin** [sourmash-bio/sourmash#1749]
I'm looking for a method that can say whether an assembly is prokaryotic or eukaryotic.  Was thinking this software might be helpful.  Do you have any preconfigured databases that have both prokaryotes and eukaryotes?

**Comment by ctb** [comment]
hi @jolespin we have a genbank database, but until recently it was too big to distribute (basically our SBT format brought in a lot of information that made it very large, and you couldn't use it without that). We have since made it possible to use smaller versions; I'll package up our old genbank database in the next few days and make it available. It still won't be fully up to date (updating it takes more time than I have at the moment!) but it should work for what you're asking - we actually use it for that ourselves ;)

**Comment by jolespin** [comment]
Thank you! That would be amazing. I vaguely recall seeing a similar database version in the past but this was before the tool was officially published.

**Comment by ctb** [comment]
hi @jolespin uploading them now, to https://drive.google.com/drive/u/0/folders/1hEbi2vYjUcw4TLwmvjpO-1s2NYulWX94

NOTE: see https://github.com/sourmash-bio/sourmash/issues/1511#issuecomment-947919554 for conversion & upload commands ;)

**Comment by ctb** [comment]
it looks like they are all there now!
