### ISSUE TITLE
hypothesis tests are now failing?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2026]
with this error:
```
...
iff_cover.command_runner.CommandError: fatal: ambiguous argument 'origin/latest...HEAD': unknown revision or path not in the working tree.
```
which seems very weird to just suddenly happen. I don't think we recently updated anything that would cause this to break, but hypothesis is not in fact version pinned in `setup.cfg` so maybe it's being caused by a new version?

**Comment by ctb** [comment]
https://pypi.org/project/hypothesis/6.46.2/ just got released. maybe that's causing problems.

**Comment by mr-eyes** [comment]
I can see from here that `git` might be involved too.

https://stackoverflow.com/questions/45096755/fatal-ambiguous-argument-origin-unknown-revision-or-path-not-in-the-working

**Comment by ctb** [comment]
yeah... but that shouldn't have been a thing that suddenly changed! 🤔

**Comment by mr-eyes** [comment]
I have just tested it locally and it worked just fine. Can you try restarting the workflow?

**Comment by mr-eyes** [comment]
I restarted the workflow, and the problem is still there.
Originated from this line https://github.com/sourmash-bio/sourmash/blob/d218f6bdbf74c7b8ee345e6fcaf095957459f7ac/tox.ini#L160

**Comment by ctb** [comment]
(it's broken on multiple PRs)

**Comment by luizirber** [comment]
I think it was https://github.com/sourmash-bio/sourmash/pull/2018, probably `checkout@3` doesn't pick `latest` and the actual PR branch. Note that the [ASV check](https://github.com/sourmash-bio/sourmash/blob/eed278e9510622a23369dffdd37b2a45c13538b3/.github/workflows/asv.yml#L16-L18) already has a similar config (because it needs both the PR and `latest` available)
