### ISSUE TITLE
Is it possible to generate the ani distance between query and db_best_hit using sourmash lca classify?

### ISSUE THREAD

**Issue by yuzie0314** [sourmash-bio/sourmash#2426]
Hi dear authors,

Our lab recently make use of `sourmash lca classify` to fast classify our genomes, and we are curious about how similar (**ANI distance**) between a query against the best hit in the db. However, we only saw the results: ID,status,superkingdom,phylum,class,order,family,genus,species,strain
bin.85.fasta,found,d__Bacteria,p__Verrucomicrobiota,c__Verrucomicrobiae,o__Verrucomicrobiales,f__Akkermansiaceae,g__Akkermansia,s__Akkermansia muciniphila,

The command we used: 
`sourmash lca classify --query *.sig --db ${db} -o ${name}-lca-classify-k21.csv`

if we cannot use this command to obtain ANI infomation, then how to do to get, any suggestions?

**Comment by ctb** [comment]
hi @yuzie0314, here's the short answer - or, well, two of them. Both of these require that `query.sig` contain just a single query sig.

* you can use `sourmash search query.sig ${db} -o query.x.db.csv --containment` to generate a CSV that contains ANI (in the `ani` column);
* you can use `sourmash compare query.sig against.sig --ani --containment` to generate a similarity matrix with ANI; here `against.sig` is the match from the database, which you can extract with `sourmash sig grep <match name> ${db} -o against.sig`.

---

## more background

The lca module predates ANI and we didn't retrofit it with ANI, in part because we have been working on alternate approaches to taxonomic analysis (see below!)

## why use `--containment` above, when calculating ANI?

If you don't specify `--containment`, the ANI numbers will be calculated from Jaccard similarity; with `--containment`, ANI will be calculated from the containment index. Our ANI maven @bluegenes suggests containment-based ANI because in some situations it matches other ANI calculations better, and (IIRC) it is never worse.

Regardless, the differences should be small ;).

## other thoughts - taxonomic classification

These days (2022 version) we suggest using `sourmash gather` and `sourmash taxonomy genome` instead of `sourmash lca classify`. You can see some commands [in the lemonade tutorial](https://sourmash.readthedocs.io/en/latest/tutorial-lemonade.html#classify-the-taxonomy-of-the-mags-update-metagenome-classification). In brief, you first run `sourmash gather query.sig ${db} -o query.x.db.csv` and then `sourmash tax genome -g query.x.db.csv -t taxonomy.csv -F human` to generate a human-readable taxonomy summary.

(You can use an LCA database for `sourmash gather`; the taxonomy in it will not be used since gather is tax-independent.)

In many cases this will match what `sourmash lca classify` outputs but we find that this performs somewhat better (more sensitively) in some situations.

Apologies for not having better docs behind all of this - we're still working on writing up the ANI benchmarking and taxonomy results!

**Comment by yuzie0314** [comment]
Dear @ctb , thank you for responding so quickly.
Here you've already described all I need to know in detail !
Looking forward to your ANI benchmarking  and taxonomy results in your future docs, which will be very helpful to us!

**Comment by ctb** [comment]
don't hesitate to ask if you have more questions!
