### ISSUE TITLE
"minimum rust version" CI checks are not being run

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2550]
not sure what's going on or where to start debugging it, but I guess creating an issue is the start ;)

every PR now is stalling here:

<img width="899" alt="Screen Shot 2023-04-06 at 4 25 58 AM" src="https://user-images.githubusercontent.com/51016/230319605-34c1ebfb-b8c8-40f2-930f-5a2d1186d43b.png">

**Comment by ctb** [comment]
hrm. doing some googling, it looks like this can happen when filters or path conditions change, and the action is no longer run all the time, but the branch protection rules still require an action of that name to be run.

but there haven't been any changes to run conditions in the `rust.yml` file in a while. still mystified.

**Comment by luizirber** [comment]
The issue is that the `rust.yml` checks only run if there are changes in Rust files. This check didn't use to be required, but I think we set it up after https://github.com/sourmash-bio/sourmash/pull/2343#issuecomment-1287829999 bumped the MSRV.

The Rust checks used to take some time to run, so maybe start running them on every PR again and see how bad it gets nowadays?

**Comment by ctb** [comment]
maybe adjust draft PRs at the same time - https://github.com/sourmash-bio/sourmash/issues/2342
