### ISSUE TITLE
'search_abund requires abundance' error when using an index

### ISSUE THREAD

**Issue by AroneyS** [sourmash-bio/sourmash#2845]
I created sketches using `sourmash sketch dna -p k=21,k=31,k=51,abund ...`
Then an index using `sourmash index -k 31 --dna --scaled 10000 ...`

But when I try to search a sketch against the index with `sourmash search -k 31 --dna ...`, I get an error:
`ERROR: 'search_abund' requires subject signatures with abundance information`

Is there a way to create an index with abundance information? I am comparing metagenomes, so `sourmash compare` runs out of memory. But I only want a subset of comparisons anyway, so `sourmash search` would be ideal.

**Comment by ctb** [comment]
hi @AroneyS, yep - the SBT index can only be used for Jaccard similarity searches, and not for angular similarity comparisons (where you are comparing abundances). This is because the Bloom filters used in the SBT don't contain abundances. (and I don't think anyone has worked out the math to see if we can use Jaccard similarity as a guide to identify likely high scoring angular similarity matches.)

I think the simplest solution here is to simply search against the list of signatures, unindexed. There's no fast indexing scheme available for abund sketches.  You can do this a few different ways -

- just give a list of files on the command line to search
- combine all your search sketches into a single zip file with `sourmash sig cat ... -o database.zip`, and then search `database.zip`
- create a text file containing a list of all paths to files containing search sketches, and pass in that text file

See https://sourmash.readthedocs.io/en/latest/command-line.html#storing-and-searching-signatures for a summary of all of this and please let me know if we miss anything (there or here) that would help!
