### ISSUE TITLE
scaled parameter not being used when running 'gather'

### ISSUE THREAD

**Issue by kebarr** [sourmash-bio/sourmash#2946]
Running as follows:

sourmash sketch dna -p k=31,scaled=1000 input_file -o output_file
sourmash gather --ksize 31 --scaled 1000 signature_file database_file -o output_file

I get a warning as shown in the screenshot:

![image](https://github.com/sourmash-bio/sourmash/assets/4732416/68468761-de70-42f8-8c77-b5d1e89c41fc)

I have tried running without specifying scaled, and get the same problem. I have installed via conda as specified in the documentation. My colleagues are not experiencing this issue. I have tried various things like reinstalling, moving 'scaled' around, adding decimal points, and cannot prevent this warning, meaning I cannot experiment with varying the scaling.

**Comment by ctb** [comment]
what is happening is that one or more of your database sketches has a scaled of 10,000, and that is triggering gather to raise the scaled value for comparisons to 10,000 in order to do the comparison. Once raised, it can't be lowered, because that would render the higher scaled match invalid for the purposes of gather.

I gather this is unexpected and that you didn't intentionally create a database with a sketch at scaled=10,000. What does `sourmash sig summarize <database>` report?

**Comment by kebarr** [comment]
Hey, thank you very much for your prompt response, I had passed the scaled parameter into the sketch command for the database, but not into the index command. I have now re-indexed with the scaled parameter and no longer have the issue.

**Comment by ctb** [comment]
fantastic, thanks for checking back!
