### ISSUE TITLE
`sourmash sig manifest` on zip files yields unusable standalone manifest CSVs

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#3009]
The `internal_location` is kept as the internal location in the zipfile, rather than the name of the zipfile:

```
% sourmash sig manifest example.sig.zip -o mf.csv
...
% cat mf.csv | cut -c, -f1
# SOURMASH-MANIFEST-VERSION: 1.0
internal_location
signatures/324074c7287ed934af4fd0a6a459aa30.sig.gz
% sourmash sig describe mf.csv
...
ERROR: Error while reading signatures from 'signatures/324074c7287ed934af4fd0a6a459aa30.sig.gz'.
```

**Comment by luizirber** [comment]
Hmm, do we want standalone manifest to be a thing? Or should they be paired with a `storage`?

I like the `internal_location` because it makes things relative, so it becomes easy to move from dir to zipfile to (http/s3/ipfs/rocksdb) as different backends for the same content (more info: https://github.com/sourmash-bio/sourmash/pull/2230#issue-1345578458).

so in this case you would call
`sourmash sig describe --storage sigs.zip mf.csv`
to explicitly set the storage.

or, maybe... a standalone manifest is a collection? This way it ties manifest + storage, and the command would be
`sourmash sig describe mf.collection`
with an option to "overwrite" the storage to point to another backend? so you could say
`sourmash sig describe --storage sigs.zip mf.collection`
or
`sourmash sig describe --storage s3://bucket-name mf.collection`
and so on

**Comment by ctb** [comment]
(it looks like `sig collect` is the right thing to use here, FWIW. will verify.)

**Comment by ctb** [comment]
Yes - verified in https://github.com/sourmash-bio/sourmash/issues/3023, updating docs in #3027 which will close this issue.
