### ISSUE TITLE
can we store md5sums in the SBT JSON file?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#339]
this would let us pick out specific signatures more easily without having to traverse through all the leaves.

**Comment by ctb** [comment]
ref node `metadata` in #244.

**Comment by ctb** [comment]
ref #993

**Comment by ctb** [comment]
also note, when using md5sum selectors #1072 being able to reach into an SBT and pull out a specific signature quickly seems like a good thing.

**Comment by ctb** [comment]
after revisiting #993 this seems to be already "done", in the sense that md5sums are stored there in several places, most specifically `metadata` but also in filename and name. What I don't know is which part(s) of this should be/could be guaranteed for SBTs in the future.

**Comment by luizirber** [comment]
> after revisiting #993 this seems to be already "done", in the sense that md5sums are stored there in several places, most specifically `metadata` but also in filename and name. What I don't know is which part(s) of this should be/could be guaranteed for SBTs in the future.

metadata. But it should probably be a dictionary, and not just the md5.

"filename" is an IPFS hash for the IPFSStorage, or might contain `_0` after the MD5 (dealing with duplicates #994) for ZipStorage and FSStorage.

I think "name" is pretty much unused (because we pull names from the signatures, not the leaf).

**Comment by ctb** [comment]
#1590 adds full manifests to SBTs, that contain all this info!
