### ISSUE TITLE
could we include LCA databases in SBTs?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#418]
thinking back to @luizirber lab meeting and SBT extensions - what about putting LCA databases into SBTs? it seems possible.

the idea would be to have them stored in a single "leaf" node, but the search could invisibly descend into the LCA db and do the search and then return/reconstruct the signatures. (I think the LCA DBs now contain sufficient information to reconstruct the signature file.) It could be a nice way to unify the current mess of SBT/signature/LCA db storage options for (say) 3.0 development.

this line of thought has some other implications - we could start thinking about how to return whatever information is available (e.g. taxonomy) for those signatures for which it is available, rather than demanding that `sourmash gather` not have tax info, `sourmash lca gather` does, etc.

**Comment by luizirber** [comment]
I was thinking about it and maybe it's time to change the name of the class from `SBT` to `SourmashIndex` or something implementation-independent. I say this because nothing stops us from keeping the LCA db out of the `nodes`, but attached to the `SBT/SourmashIndex` class. Then writing a search function that takes LCA data means checking if the LCA db is available or not (because not all `SourmashIndex` would have an LCA attached). Does this make sense?

On the storage side of things, the class is super generic: nothing stops us from stashing the LCA db right now in it... (It's pretty much a key/value abstraction for {HiddenDir, Tarfiles, IPFS, Redis}...)

**Comment by ctb** [comment]
On Mon, Feb 26, 2018 at 04:02:19AM +0000, Luiz Irber wrote:
> I was thinking about it and maybe it's time to change the name of the class from `SBT` to `SourmashIndex` or something implementation-independent. I say this because nothing stops us from keeping the LCA db out of the `nodes`, but attached to the `SBT/SourmashIndex` class. Then writing a search function that takes LCA data means checking if the LCA db is available or not (because not all `SourmashIndex` would have an LCA attached). Does this make sense?

well, you could imagine having multiple LCA DBs, no? other than that, yes.

> On the storage side of things, the class is super generic: nothing stops us from stashing the LCA db right now in it... (It's pretty much a key/value abstraction for {HiddenDir, Tarfiles, IPFS, Redis}...)

yep.

I do think we should take a look at what kind of info to include in our
JSON files so that we can figure out what they are. Right now the LCA DB,
signature, and SBT formats look pretty different. The signature format
should stay the same, perhaps :)

**Comment by ctb** [comment]
This is pretty out of date now, although the inverted index idea lives on (codename: mastiff).

I think I'm going to close this, since our understanding of & code for databases has changed so much in the last few years!
