### ISSUE TITLE
log-transform Jaccard distances 

### ISSUE THREAD

**Issue by kternus** [sourmash-bio/sourmash#491]
Given the small differences that can appear between metagenomes, could users have the option to report log-transform Jaccard distances with sourmash compare?

**Comment by ctb** [comment]
On Sat, Jun 09, 2018 at 07:21:41AM -0700, Krista Ternus wrote:
> Given the small differences that can appear between metagenomes, could users have the option to report log-transform Jaccard distances with sourmash compare?

I've been thinking about this, and while it is easy to do, there are two
problems with this approach:

* first, the significance problem. How do we estimate whether a given
  Jaccard similarity is significant or not? This was tackled in the mash
  paper and implementation, but we don't have it in sourmash yet.

* second, Jaccard similarity is dependent on the size of the metagenome(s)
  in question, and it seems potentially problematic to me to report comparisons
  between metagenomes that way.  (You could potentially end up with a situation
  where as you *increase* sequencing depth you *lose* significance of matches!)

A somewhat draconican but probably less problematic short-term approach
would be to report # of k-mers in common between metagenomes, instead.
Hmm. But then normalization becomes a problem...

Perhaps something like this, which we have implemented in scripts that
aren't (yet) part of sourmash --

* take a collection of metagenomes
* find all k-mers that are present in two or more metagenomes
* use these to calculate a kind of Jaccard similarity between all the
  metagenomes

This would provide a colletion-specific Jaccard distance matrix. Hmm.

**Comment by kternus** [comment]
Is the idea behind selecting all k-mers present in two or more metagenomes to eliminate the low abundance k-mers that may have originated from differences in sequencing depth (or sequencing errors)? Otherwise, Jaccard distances are calculated in the same way?

In my limited experience with sourmash compare, the Jaccard distances do seem to change as the abundance of k-mers within metagenomes change. Abundance could be one of the issues to account for with different depths of metagenome sequencing, but I think it's also one of the most interesting pieces of comparative information (e.g., looking at how relative levels of organisms within metagenomes change over time or under different conditions). So I'll be a fan of any path forward that salvages the comparative abundance info.

**Comment by ctb** [comment]
On Mon, Jun 11, 2018 at 02:42:35PM -0700, Krista Ternus wrote:
> Is the idea behind selecting all k-mers present in two or more metagenomes to eliminate the low abundance k-mers that may have originated from differences in sequencing depth (or sequencing errors)? Otherwise, Jaccard distances are calculated in the same way?

yes!

> In my limited experience with sourmash compare, the Jaccard distances do seem to change as the abundance of k-mers within metagenomes change. Abundance could be one of the issues to account for with different depths of metagenome sequencing, but I think it's also one of the most interesting pieces of comparative information (e.g., looking at how relative levels of organisms within metagenomes change over time or under different conditions). So I'll be a fan of any path forward that salvages the comparative abundance info.

...I agree, but also, this is an area where I just don't have any good
intuition or experience, so I don't have much to offer :).  I think we
need to play a lot more with sourmash compare for metagenomes.

**Comment by kternus** [comment]
Sounds good! Please let me know if/when you implement different ideas in sourmash compare, and I'll try it on some metagenomes that I've been analyzing to see what happens.

**Comment by ctb** [comment]
since this issue was created 3 years ago (!!) we've added a bunch of useful options to sourmash -

* we output CSVs with `--csv` that can be readily loaded into R and spreadsheet programs for log transform among other things;
* in `compare`, we support `--containment`, `--avg-containment`, and `--max-containment` which are a partial solution to the question of size dependency in metagenomes; some of this still remains to be documented tho, ref https://github.com/sourmash-bio/sourmash/issues/2224;
* similarly, the `--estimate-ani` arguments to sourmash compare (which is best used with `--max-containment` or `--containment`);
* we implemented `sourmash sig overlap` which will give details on the hash overlap between a pair of metagenomes, i.e. estimates "# of k-mers in common between metagenomes";
* we implemented `sourmash sig filter` which can be used to remove low-abundance k-mers in metagenomes;
* we also implemented `sourmash prefetch`, which directly outputs estimated # of k-mers in common between a query (metagenome) and matches;

the question of how to "properly" compare overlaps between metagenomes remains, but at least we can calculate numbers every which way 😆. so I'm going to close this issue!

**Comment by ctb** [comment]
see also discussion over in https://github.com/sourmash-bio/sourmash/issues/2226 about how ANI is effectively doing a k-normalized log transform (my words)
